"""Package the generated nifgen tree as a wheel.

Blender's add-on policy check rejects extensions that put third-party modules inside their own directory.
Usage: build_nifgen_wheel.py <nifgen dir> <version> <output wheel dir>
"""

import pathlib
import shutil
import subprocess
import sys
import tempfile

PYPROJECT = """\
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nifgen"
version = "{version}"
description = "NIF format classes generated by cobra-tools codegen"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
include = ["nifgen*"]

[tool.setuptools.package-data]
"*" = ["*.xml", "*.dll", "*.exe", "*.so", "*.dylib"]
"""


def main():
    if len(sys.argv) != 4:
        sys.exit("usage: build_nifgen_wheel.py <nifgen dir> <version> <output wheel dir>")

    src = pathlib.Path(sys.argv[1]).resolve()
    version = sys.argv[2]
    out_dir = pathlib.Path(sys.argv[3]).resolve()

    if not (src / "__init__.py").is_file():
        sys.exit(f"not a package (no __init__.py): {src}")
    out_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmp:
        build_dir = pathlib.Path(tmp)
        shutil.copytree(src, build_dir / "nifgen",
                        ignore=shutil.ignore_patterns("__pycache__"))
        (build_dir / "pyproject.toml").write_text(
            PYPROJECT.format(version=version), encoding="utf-8")

        # Build isolation is left on so pip installs setuptools
        result = subprocess.run(
            [sys.executable, "-m", "pip", "wheel", ".",
             "--no-deps", "--wheel-dir", str(out_dir)],
            cwd=build_dir, capture_output=True, text=True,
        )
        if result.returncode != 0:
            sys.exit(
                "pip wheel failed:\n"
                + (result.stdout or "")[-2000:]
                + (result.stderr or "")[-2000:]
            )

    expected = out_dir / f"nifgen-{version}-py3-none-any.whl"
    if not expected.is_file():
        built = sorted(p.name for p in out_dir.glob("nifgen-*.whl"))
        sys.exit(f"expected {expected.name}, found: {built}")

    print(f"built {expected.name}")

if __name__ == "__main__":
    main()
